# Generated by Django 4.1 on 2024-03-10 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('780528ed-2446-4c07-97ee-61edfef66ef0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
