# Generated by Django 4.1 on 2024-03-10 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('65203cbf-70f6-41f7-aa5b-9a7d54d3b544'), editable=False, primary_key=True, serialize=False),
        ),
    ]
