# Generated by Django 5.0.3 on 2024-03-09 16:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_usermodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1ffd877c-df09-4adb-885f-f06d49cf53c7"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
