# Generated by Django 4.2.11 on 2024-03-10 01:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca05509b-09fb-41f1-86ed-b98a197231fc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
