# Generated by Django 4.2.11 on 2024-03-10 02:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9b1488a3-3f74-4fe3-b822-e134a312fcb2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
