# Generated by Django 5.0.3 on 2024-03-10 02:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_usermodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("31bfc8ed-4584-4a9e-9932-7be890707c1b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
