# Generated by Django 4.2.11 on 2024-03-10 02:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de00e06a-2120-4a58-ad13-f017f6308515'), editable=False, primary_key=True, serialize=False),
        ),
    ]
