# Generated by Django 4.2.11 on 2024-03-10 03:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4827adad-e1e3-4e91-9348-9ebc2b4cd70d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
