# Generated by Django 4.2.11 on 2024-03-10 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac506689-b449-417f-8697-bd4ace3efc3f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
