# Generated by Django 4.2.11 on 2024-03-10 04:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('15cace2e-f6fc-4f7b-b1a1-7108a399077f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
