# Generated by Django 4.2.11 on 2024-03-10 04:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_usermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('634b74a4-cf30-4506-afc1-512262c1f3e3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
