# Generated by Django 4.2.11 on 2024-03-10 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_usermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bcacec63-a7c2-46b4-80a8-db2424c35fb5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
