# Generated by Django 4.2.11 on 2024-03-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='ticker',
            field=models.CharField(default='BTC', max_length=255),
            preserve_default=False,
        ),
    ]
