# Generated by Django 4.2.11 on 2024-03-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionmodel_ticker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionmodel',
            old_name='frequency',
            new_name='period',
        ),
    ]
